INSERT INTO country (id, name, short) VALUES
(1, 'Canada', 'CA');

INSERT INTO prov (id, name, short, country) VALUES
(1, 'Ontario', 'ON', 1),
(2, 'Alberta', 'AB', 1),
(3, 'British Columbia', 'BC', 1),
(4, 'Manitoba', 'MB', 1),
(5, 'New Brunswick', 'NB', 1),
(6, 'Newfoundland/Labrador', 'NL', 1),
(7, 'Northwest Territories', 'NT', 1),
(8, 'Nova Scotia', 'NS', 1),
(9, 'Nunavut', 'NU', 1),
(10, 'Prince Edward Island', 'PE', 1),
(11, 'Quebec', 'QC', 1),
(12, 'Saskatchewan', 'SK', 1),
(13, 'Yukon', 'YT', 1);

INSERT INTO city (name, prov) VALUES
('Barrie',1),
('Belleville',1),
('Brampton',1),
('Brant',1),
('Brantford',1),
('Brockville',1),
('Burlington',1),
('Cambridge',1),
('Clarence-Rockland',1),
('Cornwall',1),
('Dryden',1),
('Elliot Lake',1),
('Greater Sudbury',1),
('Guelph',1),
('Haldimand County',1),
('Hamilton',1),
('Kawartha Lakes',1),
('Kenora',1),
('Kingston',1),
('Kitchener',1),
('London',1),
('Markham',1),
('Mississauga',1),
('Niagara Falls',1),
('Norfolk County',1),
('North Bay',1),
('Orillia',1),
('Oshawa',1),
('Ottawa',1),
('Owen Sound',1),
('Pembroke',1),
('Peterborough',1),
('Pickering',1),
('Port Colborne',1),
('Prince Edward County',1),
('Quinte West',1),
('Richmond Hill',1),
('Sarnia',1),
('Sault Ste. Marie',1),
('St. Catharines',1),
('St. Thomas',1),
('Stratford',1),
('Temiskaming Shores',1),
('Thorold',1),
('Thunder Bay',1),
('Timmins',1),
('Toronto',1),
('Vaughan',1),
('Waterloo',1),
('Welland',1),
('Windsor',1),
('Woodstock',1);

INSERT INTO city (name, prov) VALUES
('Airdrie',2),
('Beaumont',2),
('Brooks',2),
('Calgary',2),
('Camrose',2),
('Chestermere',2),
('Cold Lake',2),
('Edmonton',2),
('Fort Saskatchewan',2),
('Grande Prairie',2),
('Lacombe',2),
('Leduc',2),
('Lethbridge',2),
('Lloydminster',2),
('Medicine Hat',2),
('Red Deer',2),
('Spruce Grove',2),
('St. Albert',2),
('Wetaskiwin',2);

INSERT INTO city (name, prov) VALUES
('Abbotsford',3),
('Armstrong',3),
('Burnaby',3),
('Campbell River',3),
('Castlegar',3),
('Chilliwack',3),
('Colwood',3),
('Coquitlam',3),
('Courtenay',3),
('Cranbrook',3),
('Dawson Creek',3),
('Delta',3),
('Duncan',3),
('Enderby',3),
('Fernie',3),
('Fort St. John',3),
('Grand Forks',3),
('Greenwood',3),
('Kamloops',3),
('Kelowna',3),
('Kimberley',3),
('Langford',3),
('Langley',3),
('Maple Ridge',3),
('Merritt',3),
('Nanaimo',3),
('Nelson',3),
('New Westminster',3),
('North Vancouver',3),
('Parksville',3),
('Penticton',3),
('Pitt Meadows',3),
('Port Alberni',3),
('Port Coquitlam',3),
('Port Moody',3),
('Powell River',3),
('Prince George',3),
('Prince Rupert',3),
('Quesnel',3),
('Revelstoke',3),
('Richmond',3),
('Rossland',3),
('Salmon Arm',3),
('Surrey',3),
('Terrace',3),
('Trail',3),
('Vancouver',3),
('Vernon',3),
('Victoria',3),
('West Kelowna',3),
('White Rock',3),
('Williams Lake',3);

INSERT INTO city (name, prov) VALUES
('Brandon',4),
('Dauphin',4),
('Flin Flon',4),
('Morden',4),
('Portage la Prairie',4),
('Selkirk',4),
('Steinbach',4),
('Thompson',4),
('Winkler',4),
('Winnipeg',4);

INSERT INTO city (name, prov) VALUES
('Bathurst',5),
('Campbellton',5),
('Dieppe',5),
('Edmundston',5),
('Fredericton',5),
('Miramichi',5),
('Moncton',5),
('Saint John',5);

INSERT INTO city (name, prov) VALUES
('St. Johns',6),
('Mount Pearl',6),
('Corner Brook',6);

INSERT INTO city (name, prov) VALUES
('Aklavik',7),
('Aklavik',7),
('Behchokǫ̀ (Rae-Edzo)',7),
('Délı̨nę (Fort Franklin)',7),
('Fort Good Hope',7),
('Fort Liard',7),
('Fort McPherson',7),
('Fort Providence',7),
('Fort Resolution',7),
('Fort Simpson',7),
('Fort Smith',7),
('Hay River',7),
('Inuvik',7),
('Norman Wells',7),
('Tuktoyaktuk',7),
('Tulita (Fort Norman)',7),
('Whatì (Lac La Martre)',7),
('Yellowknife',7);


INSERT INTO city (name, prov) VALUES
('Amherst',8),
('Annapolis Royal',8),
('Antigonish',8),
('Berwick',8),
('Bridgewater',8),
('Clarks Harbour',8),
('Digby',8),
('Kentville',8),
('Lockeport',8),
('Lunenburg',8),
('Mahone Bay',8),
('Middleton',8),
('Mulgrave',8),
('New Glasgow',8),
('Oxford',8),
('Pictou',8),
('Port Hawkesbury',8),
('Shelburne',8),
('Stellarton',8),
('Stewiacke',8),
('Trenton',8),
('Truro',8),
('Westville',8),
('Windsor',8),
('Wolfville',8),
('Yarmouth',8);

INSERT INTO city (name, prov) VALUES
('Iqaluit', 9);

INSERT INTO city (name, prov) VALUES
('Charlottetown', 10),
('Summerside',10);

INSERT INTO city (name, prov) VALUES
('Acton Vale',11),
('Alma',11),
('Amos',11),
('Amqui',11),
('Baie-Comeau',11),
('Baie-D Urfé',11),
('Baie-Saint-Paul',11),
('Barkmere',11),
('Beaconsfield',11),
('Beauceville',11),
('Beauharnois',11),
('Beaupré',11),
('Bécancour',11),
('Bedford',11),
('Belleterre',11),
('Beloeil',11),
('Berthierville',11),
('Blainville',11),
('Boisbriand',11),
('Bois-des-Filion',11),
('Bonaventure',11),
('Boucherville',11),
('Lac-Brome',11),
('Bromont',11),
('Brossard',11),
('Brownsburg-Chatham',11),
('Candiac',11),
('Cap-Chat',11),
('Cap-Santé',11),
('Carignan',11),
('Carleton-sur-Mer',11),
('Causapscal',11),
('Chambly',11),
('Chandler',11),
('Chapais',11),
('Charlemagne',11),
('Châteauguay',11),
('Château-Richer',11),
('Chibougamau',11),
('Clermont',11),
('Coaticook',11),
('Contrecoeur',11),
('Cookshire-Eaton',11),
('Côte Saint-Luc',11),
('Coteau-du-Lac',11),
('Cowansville',11),
('Danville',11),
('Daveluyville',11),
('Dégelis',11),
('Delson',11),
('Desbiens',11),
('Deux-Montagnes',11),
('Disraeli',11),
('Dolbeau-Mistassini',11),
('Dollard-des-Ormeaux',11),
('Donnacona',11),
('Dorval',11),
('Drummondville',11),
('Dunham',11),
('Duparquet',11),
('East Angus',11),
('Estérel',11),
('Farnham',11),
('Fermont',11),
('Forestville',11),
('Fossambault-sur-le-Lac',11),
('Gaspé',11),
('Gatineau',11),
('Gracefield',11),
('Granby',11),
('Grande-Rivière',11),
('Hampstead',11),
('Hudson',11),
('Huntingdon',11),
('Joliette',11),
('Kingsey Falls',11),
('Kirkland',11),
('La Malbaie',11),
('La Pocatière',11),
('La Prairie',11),
('La Sarre',11),
('La Tuque',11),
('Lac-Delage',11),
('Lachute',11),
('Lac-Mégantic',11),
('Lac-Saint-Joseph',11),
('Lac-Sergent',11),
('L Ancienne-Lorette',11),
('L Assomption',11),
('Laval',11),
('Lavaltrie',11),
('Lebel-sur-Quévillon',11),
('L Épiphanie',11),
('Léry',11),
('Lévis',11),
('L Île-Cadieux',11),
('L Île-Dorval',11),
('L Île-Perrot',11),
('Longueuil',11),
('Lorraine',11),
('Louiseville',11),
('Macamic',11),
('Magog',11),
('Malartic',11),
('Maniwaki',11),
('Marieville',11),
('Mascouche',11),
('Matagami',11),
('Matane',11),
('Mercier',11),
('Métabetchouan–Lac-à-la-Croix',11),
('Métis-sur-Mer',11),
('Mirabel',11),
('Mont-Joli',11),
('Mont-Laurier',11),
('Montmagny',11),
('Montreal',11),
('Montreal West',11),
('Montréal-Est',11),
('Mont-Saint-Hilaire',11),
('Mont-Tremblant',11),
('Mount Royal',11),
('Murdochville',11),
('Neuville',11),
('New Richmond',11),
('Nicolet',11),
('Normandin',11),
('Notre-Dame-de-l Île-Perrot',11),
('Notre-Dame-des-Prairies',11),
('Otterburn Park',11),
('Paspébiac',11),
('Percé',11),
('Pincourt',11),
('Plessisville',11),
('Pohénégamook',11),
('Pointe-Claire',11),
('Pont-Rouge',11),
('Port-Cartier',11),
('Portneuf',11),
('Prévost',11),
('Princeville',11),
('Québec',11),
('Repentigny',11),
('Richelieu',11),
('Richmond',11),
('Rigaud',11),
('Rimouski',11),
('Rivière-du-Loup',11),
('Rivière-Rouge',11),
('Roberval',11),
('Rosemère',11),
('Rouyn-Noranda',11),
('Saguenay',11),
('Saint-Augustin-de-Desmaures',11),
('Saint-Basile',11),
('Saint-Basile-le-Grand',11),
('Saint-Bruno-de-Montarville',11),
('Saint-Césaire',11),
('Saint-Charles-Borromée',11),
('Saint-Colomban',11),
('Saint-Constant',11),
('Sainte-Adèle',11),
('Sainte-Agathe-des-Monts',11),
('Sainte-Anne-de-Beaupré',11),
('Sainte-Anne-de-Bellevue',11),
('Sainte-Anne-des-Monts',11),
('Sainte-Anne-des-Plaines',11),
('Sainte-Catherine',11),
('Sainte-Catherine-de-la-Jacques-Cartier',11),
('Sainte-Julie',11),
('Sainte-Marguerite-du-Lac-Masson',11),
('Sainte-Marie',11),
('Sainte-Marthe-sur-le-Lac',11),
('Sainte-Thérèse',11),
('Saint-Eustache',11),
('Saint-Félicien',11),
('Saint-Gabriel',11),
('Saint-Georges',11),
('Saint-Hyacinthe',11),
('Saint-Jean-sur-Richelieu',11),
('Saint-Jérôme',11),
('Saint-Joseph-de-Beauce',11),
('Saint-Joseph-de-Sorel',11),
('Saint-Lambert',11),
('Saint-Lazare',11),
('Saint-Lin-Laurentides',11),
('Saint-Marc-des-Carrières',11),
('Saint-Ours',11),
('Saint-Pamphile',11),
('Saint-Pascal',11),
('Saint-Pie',11),
('Saint-Raymond',11),
('Saint-Rémi',11),
('Saint-Sauveur',11),
('Saint-Tite',11),
('Salaberry-de-Valleyfield',11),
('Schefferville',11),
('Scotstown',11),
('Senneterre',11),
('Sept-Îles',11),
('Shawinigan',11),
('Sherbrooke',11),
('Sorel-Tracy',11),
('Stanstead',11),
('Sutton',11),
('Témiscaming',11),
('Témiscouata-sur-le-Lac',11),
('Terrebonne',11),
('Thetford Mines',11),
('Thurso',11),
('Trois-Pistoles',11),
('Trois-Rivières',11),
('Valcourt',11),
('Val-d Or',11),
('Val-des-Sources',11),
('Varennes',11),
('Vaudreuil-Dorion',11),
('Victoriaville',11),
('Ville-Marie',11),
('Warwick',11),
('Waterloo',11),
('Waterville',11),
('Westmount',11),
('Windsor',11);


INSERT INTO city (name, prov) VALUES
('Estevan',12),
('Flin Flon',12),
('Humboldt',12),
('Lloydminster',12),
('Martensville',12),
('Meadow Lake',12),
('Melfort',12),
('Melville',12),
('Moose Jaw',12),
('North Battleford',12),
('Prince Albert',12),
('Regina',12),
('Saskatoon',12),
('Swift Current',12),
('Warman',12),
('Weyburn',12),
('Yorkton',12);

INSERT INTO city (name, prov) VALUES
('Whitehorse', 13);









